#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
SCRIPTPATH/down

#boot compton if it exists
if [ -x "$(command -v picom)" ]; then
  picom --experimental-backends &> /dev/null & 
fi

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-fill "$SCRIPTPATH"/background.jpg
fi

echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/commands.pipe

#boot polybar based on the number of monitors found
#if [ -x "$(command -v polybar)" ]; then
#  pkill polybar
#  monitors="$(polybar -m | sed s/:.*// | tac)"
#  while read -r display; do
#    MONITOR=$display polybar -c "bash ~/.config/polybar/launch.sh --grayblocks" mainbar &> /dev/null &
#  done <<< "$monitors"
#  exit 0
#fi
bash ~/.config/polybar/launch.sh --grayblocks
